language: ruby

services:
  - postgresql

before_install:
  - gem install bundler

script:
  - bundle exec rspec spec/*

after_script:
  - bundle exec coveralls push

after_success:
- CI=true TRAVIS=true coveralls --verbose
