require "sinatra/base"
require "sinatra/config_file"

class MyApp < Sinatra::Base
register Sinatra::ConfigFile

config_file 'path/to/config.yml'

get '/' do
# Configurations will go here
end

  # The rest of your modular application code goes here...
end