development:
  adapter: postgresql
  encoding: unicode
  database: learn
  pool: 2
  username: simiyu
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: learn_test
  pool: 2
  username: simiyu
  password: 